dist: bionic

language: python
python:
    # - 3.6
    # - 3.7
    - 3.8

apt-packages:
    - sqlite3

before_install:
    - pip3 install invoke
    # InvenTree Setup
    - git clone https://github.com/inventree/InvenTree/
    - cp tests/files/inventree_default_db.sqlite3 InvenTree/
    - cd InvenTree/
    - invoke install
    - invoke migrate
    - cd ..
    # Ki-nTree setup
    # Remove python-coveralls as not maintained
    - pip uninstall python-coveralls -y
    - invoke install
    
install: skip

script: invoke test

after_success:
    - coveralls