dist: bionic

branches:
  only:
  - master
  
language: python
python:
    - 3.6
    - 3.7
    - 3.8

apt-packages:
    - sqlite3

before_install:
    - pip install invoke
    # InvenTree Setup
    - git clone https://github.com/inventree/InvenTree/
    - cp tests/files/inventree_default_db.sqlite3 InvenTree/
    - cd InvenTree/ && invoke install && invoke migrate && cd -
    # Ki-nTree setup
    # Remove inventree as conflict with submodule
    - pip uninstall inventree -y
    - invoke install
    - cp tests/files/results.tgz search/
    - cd search/ && tar xvf results.tgz && cd -
    
install: skip

script: invoke test

after_success:
    - coveralls