dist: bionic

language: python
python:
    # - 3.6
    # - 3.7
    - 3.8

apt-packages:
    - sqlite3

before_install:
    - pip3 install invoke
    - invoke install
    # InvenTree Setup
    - git clone https://github.com/inventree/InvenTree/
    - cp tests/files/inventree_default_db.sqlite3 InvenTree/
    - cd InvenTree/
    - invoke install
    - invoke migrate
    - cd ..

install: skip

jobs:
  include:
    - script: cd InvenTree/InvenTree/ && python manage.py runserver
    - script: invoke test

after_success:
    - coveralls