dist: bionic

language: python
python:
    - 3.6
    - 3.7
    - 3.8

apt-packages:
    - sqlite3

before_install:
    - pip3 install invoke
    - invoke clean
    - invoke install
    # InvenTree Setup
    - git clone https://github.com/inventree/inventree/
    - cp tests/files/inventree_default_db.sqlite3 inventree/inventree/
    - cd inventree/
    - invoke install
    - invoke migrate

script:
    - invoke test

after_success:
    - coveralls