dist: bionic

language: python
python:
    - 3.6
    - 3.7
    - 3.8

# addons:
#     update: true
#     apt-packages:
#         - python3.6-dev
#         - python3.7-dev
#         - python3.8-dev

before_install:
    - pip3 install invoke
    - invoke install
    - cd search/ && tar xvf results.tgz && cd -

script:
    - invoke test

after_success:
    - coveralls